version: '3.9'

services:
  db:
    image: postgres:15-alpine
    environment:
        POSTGRES_DB: 'postgres_db'
        POSTGRES_USER: 'postgres'
        POSTGRES_PASSWORD: '1234'
        POSTGRES_HOST: '127.0.0.1'
    ports:
      - "5432:5432"
    volumes:
     - /postgres/db:/var/lib/postgresql/data

  web:
    build: .
    restart: on-failure
    volumes:
      - ./django_pet_project:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
