# Generated by Django 4.2.1 on 2023-05-16 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('message', models.TextField(max_length=1000)),
                ('created_it', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Обратная_связь',
                'verbose_name_plural': 'Обратная_связь',
            },
        ),
    ]
