# Generated by Django 4.2.1 on 2023-05-09 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name': 'Обратная_связь', 'verbose_name_plural': 'Обратная_связь'},
        ),
    ]
