# Generated by Django 4.2.1 on 2023-05-16 10:49

from django.db import migrations, models
import foto_gallery.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_foto', models.CharField(max_length=200, verbose_name='Название')),
                ('created_it', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('image', models.ImageField(blank=True, upload_to=foto_gallery.models.get_upload_path, verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Фотогалерея',
                'verbose_name_plural': 'Фотогалерея',
            },
        ),
    ]
